// Pulls in the library's `declare module '*.vue'` shim (needed to type-check
// `src/index.ts`'s `import VImage from './components/VImage.vue'` when
// resolved through this app's `vue-image-kit` alias) into this project's
// compilation. Can't just add `src/env.d.ts` to .nuxt/tsconfig.json's
// `include` — that file is regenerated by `nuxt prepare` on every install.
/// <reference path="../src/env.d.ts" />
