import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import type { ImageRequest } from './plugin.js'

export interface TypesFile {
  record(request: ImageRequest): void
  flush(): void
}

const BUILT_IN_QUERIES = new Set([
  'vik',
  'hazehash',
  'thumbhash',
  'blurhash',
  'color',
  'size',
  'preview',
  'aspect',
  'placeholder',
  'placeholder=hazehash',
  'placeholder=blurhash',
  'placeholder=thumbhash',
  'placeholder=color',
])

const HEADER = 'generated by vue-image-kit (types option of the Vite plugin) — delete to regenerate'

const VIK_META = `{
    name: string
    src: string
    srcset: string
    webp: string
    avif: string
    width: number
    height: number
    placeholder: string
    blurhash: string
    thumbhash: string
    [key: string]: string | number
  }`

const PLACEHOLDER_LOOKUP = `{
    hazehash?: string
    blurhash?: string
    thumbhash?: string
    placeholderColor?: string
    placeholder?: string
    width?: number
    height?: number
    color?: string
    preview?: string
    size?: { width: number; height: number }
    aspect?: number
  }`

export function normalizeQuery(query: string): string {
  return query
    .split('&')
    .filter((part) => part !== '' && part !== 'import' && !/^t=\d+$/.test(part))
    .join('&')
}

export function typeFor(request: ImageRequest): string {
  if (request.type === 'vik') return VIK_META
  if (request.type === 'placeholder') return PLACEHOLDER_LOOKUP
  if (request.type === 'size') return '{ width: number; height: number }'
  if (request.type === 'aspect') return 'number'
  return 'string'
}

function block(query: string, type: string): string {
  const name = `*?${query}`.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  return `declare module '${name}' {\n  const value: ${type}\n  export default value\n}\n`
}

function readBlocks(path: string): Map<string, string> {
  const blocks = new Map<string, string>()
  if (!existsSync(path)) return blocks
  const text = readFileSync(path, 'utf8')
  const pattern = /declare module '\*\?((?:[^'\\]|\\.)*)' \{[\s\S]*?\n\}\n/g
  for (const match of text.matchAll(pattern)) {
    const query = (match[1] as string).replace(/\\(['\\])/g, '$1')
    blocks.set(query, match[0])
  }
  return blocks
}

export function createTypesFile(path: string): TypesFile {
  const blocks = readBlocks(path)
  let dirty = false
  let timer: ReturnType<typeof setTimeout> | null = null

  function render(): string {
    const body = [...blocks.keys()]
      .sort()
      .map((query) => blocks.get(query) as string)
      .join('\n')
    return `/* ${HEADER} */\n\n${body}`
  }

  function flush(): void {
    if (timer) clearTimeout(timer)
    timer = null
    if (!dirty) return
    dirty = false
    const next = render()
    try {
      if (existsSync(path) && readFileSync(path, 'utf8') === next) return
      mkdirSync(dirname(path), { recursive: true })
      writeFileSync(path, next, 'utf8')
    } catch {
      return
    }
  }

  return {
    record(request) {
      const query = normalizeQuery(request.query)
      if (BUILT_IN_QUERIES.has(query) || blocks.has(query)) return
      blocks.set(query, block(query, typeFor(request)))
      dirty = true
      if (timer) return
      timer = setTimeout(flush, 300)
      timer.unref?.()
    },
    flush,
  }
}
