import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import type { PlaceholderData, PlaceholderMode } from './compute.js'
import { child, children, propertyKey, type AstNode } from '../scan/ast.js'

export type ManifestEntries = Record<string, PlaceholderData>

export type ProgramParser = (code: string) => AstNode | null

const WRAPPERS = new Set(['TSAsExpression', 'TSSatisfiesExpression', 'ParenthesizedExpression'])

const ENTRY_FIELDS = ['blurhash', 'thumbhash', 'color', 'width', 'height'] as const

export function entryForMode(data: PlaceholderData, mode: PlaceholderMode): PlaceholderData {
  const entry: PlaceholderData = {}
  if (mode === 'blurhash' && data.blurhash) entry.blurhash = data.blurhash
  if (mode === 'thumbhash' && data.thumbhash) entry.thumbhash = data.thumbhash
  if (data.color) entry.color = data.color
  if (data.width && data.height) {
    entry.width = data.width
    entry.height = data.height
  }
  return entry
}

function sortEntry(entry: PlaceholderData): PlaceholderData {
  const sorted: PlaceholderData = {}
  for (const field of ENTRY_FIELDS) {
    if (entry[field] !== undefined) (sorted as Record<string, unknown>)[field] = entry[field]
  }
  return sorted
}

function unwrapNode(node: AstNode | undefined): AstNode | undefined {
  let current = node
  while (current && WRAPPERS.has(current.type)) current = child(current, 'expression')
  return current
}

function literalValue(node: AstNode | undefined): unknown {
  const value = unwrapNode(node)
  if (!value) return undefined
  if (value.type === 'StringLiteral' || value.type === 'NumericLiteral') return value['value']
  if (value.type === 'TemplateLiteral' && children(value, 'expressions').length === 0) {
    return (children(value, 'quasis')[0]?.['value'] as { cooked?: string } | undefined)?.cooked
  }
  if (value.type === 'ObjectExpression') {
    const result: Record<string, unknown> = {}
    for (const property of children(value, 'properties')) {
      const key = propertyKey(property)
      if (key !== undefined) result[key] = literalValue(child(property, 'value'))
    }
    return result
  }
  return undefined
}

function manifestObject(program: AstNode): AstNode | undefined {
  for (const statement of children(program, 'body')) {
    if (statement.type === 'ExportDefaultDeclaration') {
      const declaration = unwrapNode(child(statement, 'declaration'))
      if (declaration?.type === 'ObjectExpression') return declaration
    }
    const declaration =
      statement.type === 'ExportNamedDeclaration' ? child(statement, 'declaration') : statement
    if (declaration?.type !== 'VariableDeclaration') continue
    for (const declarator of children(declaration, 'declarations')) {
      const init = unwrapNode(child(declarator, 'init'))
      if (init?.type === 'ObjectExpression') return init
    }
  }
  return undefined
}

function readGeneratedFormat(text: string): ManifestEntries {
  const start = text.indexOf('= {')
  const end = text.lastIndexOf('\n}')
  if (start < 0 || end < start) return {}
  const body = text.slice(start + 2, end + 2).replace(/,(\s*})\s*$/, '$1')
  return JSON.parse(body) as ManifestEntries
}

export function readManifest(path: string, parse?: ProgramParser): ManifestEntries {
  if (!existsSync(path)) return {}
  const text = readFileSync(path, 'utf8')
  try {
    if (path.endsWith('.json')) return JSON.parse(text) as ManifestEntries
    const program = parse?.(text)
    const object = program ? manifestObject(program) : undefined
    if (object) return literalValue(object) as ManifestEntries
    return readGeneratedFormat(text)
  } catch {
    return {}
  }
}

export function renderManifest(entries: ManifestEntries, path: string, typeImport: string): string {
  const keys = Object.keys(entries).sort()
  if (path.endsWith('.json')) {
    const ordered: ManifestEntries = {}
    for (const key of keys) ordered[key] = sortEntry(entries[key]!)
    return `${JSON.stringify(ordered, null, 2)}\n`
  }
  const lines = keys.map(
    (key) => `  ${JSON.stringify(key)}: ${JSON.stringify(sortEntry(entries[key]!))},`,
  )
  return [
    `import type { PlaceholderManifest } from '${typeImport}'`,
    '',
    '// Generated by `vue-image-kit placeholders` — re-run the command instead of editing by hand.',
    `const placeholders: PlaceholderManifest = {`,
    ...lines,
    '}',
    '',
    'export default placeholders',
    '',
  ].join('\n')
}

export function writeManifest(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return false
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf8')
  return true
}
